[local]
local-bootnode ansible_connection=local 

local-beacon0 ansible_connection=local  privatekey={{KEY.beacon.0}} node_port={{beacon.0.NODE_PORT}} rpc_port={{beacon.0.RPC_PORT}} ws_port={{beacon.0.WS_PORT}}
local-beacon1 ansible_connection=local  privatekey={{KEY.beacon.1}} node_port={{beacon.1.NODE_PORT}} rpc_port={{beacon.1.RPC_PORT}} ws_port={{beacon.1.WS_PORT}}
local-beacon2 ansible_connection=local  privatekey={{KEY.beacon.2}} node_port={{beacon.2.NODE_PORT}} rpc_port={{beacon.2.RPC_PORT}} ws_port={{beacon.2.WS_PORT}}
local-beacon3 ansible_connection=local  privatekey={{KEY.beacon.3}} node_port={{beacon.3.NODE_PORT}} rpc_port={{beacon.3.RPC_PORT}} ws_port={{beacon.3.WS_PORT}}

local-shard0-0 ansible_connection=local  privatekey={{KEY.shard.0.0}} node_port={{shard.0.0.NODE_PORT}} rpc_port={{shard.0.0.RPC_PORT}} ws_port={{shard.0.0.WS_PORT}}
local-shard0-1 ansible_connection=local  privatekey={{KEY.shard.0.1}} node_port={{shard.0.1.NODE_PORT}} rpc_port={{shard.0.1.RPC_PORT}} ws_port={{shard.0.1.WS_PORT}}
local-shard0-2 ansible_connection=local  privatekey={{KEY.shard.0.2}} node_port={{shard.0.2.NODE_PORT}} rpc_port={{shard.0.2.RPC_PORT}} ws_port={{shard.0.2.WS_PORT}}
local-shard0-3 ansible_connection=local  privatekey={{KEY.shard.0.3}} node_port={{shard.0.3.NODE_PORT}} rpc_port={{shard.0.3.RPC_PORT}} ws_port={{shard.0.3.WS_PORT}}

local-shard1-0 ansible_connection=local  privatekey={{KEY.shard.1.0}} node_port={{shard.1.0.NODE_PORT}} rpc_port={{shard.1.0.RPC_PORT}} ws_port={{shard.1.0.WS_PORT}}
local-shard1-1 ansible_connection=local  privatekey={{KEY.shard.1.1}} node_port={{shard.1.1.NODE_PORT}} rpc_port={{shard.1.1.RPC_PORT}} ws_port={{shard.1.1.WS_PORT}}
local-shard1-2 ansible_connection=local  privatekey={{KEY.shard.1.2}} node_port={{shard.1.2.NODE_PORT}} rpc_port={{shard.1.2.RPC_PORT}} ws_port={{shard.1.2.WS_PORT}}
local-shard1-3 ansible_connection=local  privatekey={{KEY.shard.1.3}} node_port={{shard.1.3.NODE_PORT}} rpc_port={{shard.1.3.RPC_PORT}} ws_port={{shard.1.3.WS_PORT}}

local-stake1-0 ansible_connection=local  privatekey={{KEY.stake.1.0}} node_port={{stake.1.0.NODE_PORT}} rpc_port={{stake.1.0.RPC_PORT}} ws_port={{stake.1.0.WS_PORT}}
local-stake1-1 ansible_connection=local  privatekey={{KEY.stake.1.1}} node_port={{stake.1.1.NODE_PORT}} rpc_port={{stake.1.1.RPC_PORT}} ws_port={{stake.1.1.WS_PORT}}
local-stake1-2 ansible_connection=local  privatekey={{KEY.stake.1.2}} node_port={{stake.1.2.NODE_PORT}} rpc_port={{stake.1.2.RPC_PORT}} ws_port={{stake.1.2.WS_PORT}}
local-stake1-3 ansible_connection=local  privatekey={{KEY.stake.1.3}} node_port={{stake.1.3.NODE_PORT}} rpc_port={{stake.1.3.RPC_PORT}} ws_port={{stake.1.3.WS_PORT}}
local-stake1-4 ansible_connection=local  privatekey={{KEY.stake.1.4}} node_port={{stake.1.4.NODE_PORT}} rpc_port={{stake.1.4.RPC_PORT}} ws_port={{stake.1.4.WS_PORT}}

