ansible_ssh_private_key_file: '/Users/hungautonomous/stagging'
ansible_ssh_user: 'root'
host_key_checking: false

bootnode: "157.245.128.19"
fullnode:
  0:
    IP: "157.245.169.72"
    NODE_PORT: 19004
    RPC_PORT: 9334
    WS_PORT: 19334
  1: 
    IP: "157.245.169.72"
    NODE_PORT: 19005
    RPC_PORT: 9335
    WS_PORT: 19335
KEY:
  fullnode:
    0: ''
    1: ''