[master:children]
beacon
shard0
shard1
boot

[boot]
bootnode ansible_ssh_host={{beacon.0.IP}} 

[beacon]
beacon0 ansible_ssh_host={{beacon.0.IP}} spendingkey={{KEY.beacon.0}} node_port={{beacon.0.NODE_PORT}} rpc_port={{beacon.0.RPC_PORT}}

[shard0]
shard0-0 ansible_ssh_host={{shard.0.0.IP}} spendingkey={{KEY.shard.0.0}} node_port={{shard.0.0.NODE_PORT}} rpc_port={{shard.0.0.RPC_PORT}}

[shard1]
shard1-0 ansible_ssh_host={{shard.1.0.IP}} spendingkey={{KEY.shard.1.0}} node_port={{shard.1.0.NODE_PORT}} rpc_port={{shard.1.0.RPC_PORT}}
