bootnode: "127.0.0.1"
beacon:
  0: 
    IP: "127.0.0.1"
    NODE_PORT: 9000
    RPC_PORT: 9334
  1: 
    IP: "127.0.0.1"
    NODE_PORT: 9001
    RPC_PORT: 9335
  2: 
    IP: "127.0.0.1"
    NODE_PORT: 9002
    RPC_PORT: 9336
  # 3: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9003
  #   RPC_PORT: 9337
  # 4: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9004
  #   RPC_PORT: 9338
  # 5: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9005
  #   RPC_PORT: 9339
  # 6: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9006
  #   RPC_PORT: 9340
  # 7: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9007
  #   RPC_PORT: 9341
  # 8: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9008
  #   RPC_PORT: 9342
  # 9: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9009
  #   RPC_PORT: 9343
  # 10: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9010
  #   RPC_PORT: 9344
  # 11: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9011
  #   RPC_PORT: 9345
  # 12: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9012
  #   RPC_PORT: 9346
  # 13: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9013
  #   RPC_PORT: 9347
  # 14: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9014
  #   RPC_PORT: 9348
  # 15: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9015
  #   RPC_PORT: 9349
  # 16: 
  #   IP: "127.0.0.1"
  #   NODE_PORT: 9016
  #   RPC_PORT: 9350
shard:
  0:
    0: 
      IP: "127.0.0.1"
      NODE_PORT: 11003
      RPC_PORT: 10337
    1: 
      IP: "127.0.0.1"
      NODE_PORT: 11004
      RPC_PORT: 10338
    2: 
      IP: "127.0.0.1"
      NODE_PORT: 11005
      RPC_PORT: 10339
    # 3: 
    #   IP: "127.0.0.1"
    #   NODE_PORT: 11006
    #   RPC_PORT: 10340
  1:
    0: 
      IP: "127.0.0.1"
      NODE_PORT: 12003
      RPC_PORT: 11337
    1: 
      IP: "127.0.0.1"
      NODE_PORT: 12004
      RPC_PORT: 11338
    2: 
      IP: "127.0.0.1"
      NODE_PORT: 12005
      RPC_PORT: 11339
    # 3: 
    #   IP: "127.0.0.1"
    #   NODE_PORT: 12006
    #   RPC_PORT: 11340

KEY:
  beacon:
    0: '112t8rxTdWfGCtgWvAMHnnEw9vN3R1D7YgD1SSHjAnVGL82HCrMq9yyXrHv3kB4gr84cejnMZRQ973RyHhq2G3MksoTWejNKdSWoQYDFf4gQ'
    1: '112t8rnXDNYL1RyTuT85JXeX7mJg1Sc6tCby5akSM7pfEGApgAx83X8C46EDu6dFAK6MVcWfQv2sfTk5nV9HqU3jrkrWdhrmi9z34jEhgHak'
    2: '112t8rnXmEeG5zsS7rExURJfqaRZhm6r4Pypkeag2gprdhtgDpen3LwV68x1nDPRYz2zhyhJTJCGvq1tUx4P1dvrdxF9W9DH7ME7PeGN2ohZ'
    3: "112t8rnXZD2GmbVAP3xBefJaorCgebytpoRK1oAzcgoNNSVtXzoRTu21KeSmnRbzvd7qMJd1mTcsqFS1CGZ8UpY4mFRZzBa69aVcFWpLXuRv"
    4: "112t8rnXxR8GDWhm5Shn8GAaCHFNLXyFpz4Ln8wCcDCkmnJLNU4msYvCaXShxcp2mEoUxyVpGcyYtk2JzntZFZ4DNpwAc7QVif6r2oeLj2Qo"
    5: "112t8rnYBW9trs5rzxrMzLU5AnzngQhbp6X4c3xyamFkWU7PwWRq6gprDkm6mf3ZjxaeYQmSpe3xorpWHo3JLLZFHCHSgqd8u19XkVuMGz1M"
    6: "112t8rnXRwPSzrQFjCbDnciutb3K8MnbGVAxLzaYK8UhGjr8JKbR4CwGmiibz17CieTUxtgPEzqLiufsxG7kwfNEdh6PjWtqvcdULpkHsGVS"
    7: "112t8rnYAR1CmGRPjhGSeSSDgQgzEB1M8asjUwhN63CAwh74uTisQRbSUvXG6dbf3hmS63gAkudevHc4JLVeTboNXMr6c5cVPAHXgqtekLcc"
    8: "112t8rnYbn9vXZpmkn7gN71PY5qtF4i8vutwfKEJV4wdw9YBnJnooRumw9iucKY3XSeAuDNLwGK9xYKimUeHrogqu7rYyVTbqRsX3knnHeSJ"
    9: "112t8rnZEM3qDq5eiFwmhznYdZiuEAxhEFNpvu3PqVua51vDhhEpwJ3WH14G5UazfXSpY2BD7i1dac74eChhyQDm38x5ZJCfs1F1wTr4eDNh"
    10: "112t8rnZhsatLCpVW8E2PccMbQD64CHybdFxbiAMbiF7nSuQ9nY5gMxvueVi9JVmVgJTjm4CWFGSxbMN3ouMbKoaygkk1ru5inqsaRfWo6DQ"
    11: "112t8rnaRzEQ4vingMe1ZSjuC83eKuXr2tPQhuvp7JsURJdHa5TEhFQRzY1zi8RraKqXzcWPxrSfVFxeeXUj1MFPUtCh7ji3PdCFzZvMe36Z"
    12: "112t8rnayWyHLvZboXXz5SoJ7C8TqGxXJYBkbU8RDq12x6R7ck7q8STuCZpTbZ7ZdX3NqM2iu3sVAmbkG5RKUMvLTgUiMcTu6w9k2zDCSwLN"
    13: "112t8rnbaTV3J9dbWcddPwc1vNacJckg3qpS3RUfybE1e5rEop7zRKaEKUUWA7aKgLjAPyMpNZ7h6zSGedMB7CAKp4wxVQJVd1vLQyJCB1b6"
    14: "112t8rnbuoERjJSvDScFhJh6dPChenaYcGwnfXFGB9CpKxYavM4xHmuX3J9HRMMpnpLsABaWJuxyqi9ch7Cwf6y1sUTA4KCmECPZkj6BXzNp"
    15: "112t8rncXpqe4cHE4yrwowipdYuGturFovzHWuWJWQPe6zqmDGmEAASnbDbeXvq9GhtRiH2zeyVDGGsxYZYpBiUV14jiGrZ5xiXCxgvtrhPe"
    16: "112t8rndAXCuZ96NFFubQmHCytTBihK9gjasF3nrvawkgWTiNTRq6vvoVgRUhNPaxwswxtoPJ25EGNKo2Sr6dNeUYbvcuYdM1SoebND8qGNT"
    17: "112t8rnduMvZ6GSsgWaBhBaF6gknBYqPT6gy1GGnjDwrFNFKhGqJ5gNzT7daYysV8a7WnCaknn24NUf7E69MNWm8WCN841ZGm33bC3y47pUq"
    18: "112t8rneGa8Hwc8cw93xe14aoXrd5T1fhWe1nohhPXwe8SAvsxMijdpvvkNRd6rLU5KB65AfywpYa9tmu4ifcTyucXwJJcJ9yLSEp7KhYGT5"
    19: "112t8rnesT45PaMb4FymSe18exVWfwJUJCV7fUZ86LV3vvADbbGCs7eiMrM1a7ifMGpCfoDcVEZKC7aPXrfPqRbnZWqaUhVP4gebfmSsqwKU"
    20: "112t8rnfcTU5rdWyj8bFboJsVvRW8g7KPTGARsNmvs3nYn23XmJicvp4vyj17LpKs8MgjgXpqRQxAizTi2JCEfjVmYEXqZMUhQQaZVN111CS"
    21: "112t8rngAy7uR1VvCKtVcLTCXYrY72FEn4z4H13QCWsvaFzoJt3DpZnyVLGcg7GXcTK7uV729yKe9Ayp6XYdvwExtMZGCCb5fSCgktmNMn1C"
    22: "112t8rngZqsK5Tos41TuVvLNfLdx9bneACnPBphnzM6ueZZD4ExoYc1T6ajToRd6AKBhiF28m9crd4L6RTuLLzfC8GqwdKFGmrHVfqGFzEPX"
    23: "112t8rnh7F9ByXV97LKsmBSqton4yqqYNfKi6Ty2e5mmnd86ovC4QdbpVgSWcz5ygE7xWX74XHcqRE4VnZTXMGrH2z1sPKfDKwhuB3L1zjr1"
  shard:
    0:
      0: '112t8rqGc71CqjrDCuReGkphJ4uWHJmiaV7rVczqNhc33pzChmJRvikZNc3Dt5V7quhdzjWW9Z4BrB2BxdK5VtHzsG9JZdZ5M7yYYGidKKZV'
      1: '112t8ruNDweRqN4LvP1FaxjWWoVjDqbhtqQyjx52xtq3rpcRuPhqtwApvuNYpj78TAdZAqDsy4ewwgaEdCQWqK5VAXdBPfWKkMD3QbeRSaSJ'
      2: '112t8roGSduAqZKFWWdRMzVazM5qDN6xzii4wWwbn6r4uEbTfEVN2o9sHY9kvHpouUXnhm9HnUcWSUTDvyBDgRLTVqqj5pgdmD6QJoC99bRq'
      3: '112t8ruqNDGrL9LqCvgZZuPGANgJ2mQEYogEmuSfpUFgaCf2cpPMvYpDUQzX4xWYaFXbfrfsNdjK9gZn2zS8tXhaywgAp1Pu8Bra2PurHtw6'
    1:
      0: '112t8rpxJvKj42esCYsnShYnbe67yERdjrPmWcDWCcTyM6W4Nst3yyBkidWEu2M2M5H5cKwVMtzBLM6XWyqQrB4L4QK2GJFyaBQhRwgC8Vz6'
      1: '112t8rqNdNmv4Z1WeR9Lj8Us9qABCCSFRNJf1fQ3yr2v9WKkkxxHQZzDX6zF1GYq3hC6qBE9GMo9hJgrBq7irZ2qc3HSMaPLMkMTE76YH4Jc'
      2: '112t8rpcsM9MQtbinYKXphEmCM1xmd4SmsFupTmNp2kBkboVSsAJj3r7bZ4CwDAdHapc5hdsrNNgoCo7a6MJkc93UuSu875Y6ewNLMDXtgyr'
      3: "112t8rt27RFqHVYpj11Q7tVsjE9sxFQESe53BChdXaySoRDDo3vqfrSB4sce2HruiLh9T2aq6fSScV48XBBi5jVSoSXnd1ubMRLgBYRRqqHq"