ansible_ssh_private_key_file: '/Users/hungautonomous/stagging'
ansible_ssh_user: 'root'
host_key_checking: false

bootnode: "68.183.229.181"
beacon:
  0: 
    IP: "68.183.229.181"
    NODE_PORT: 9000
    RPC_PORT: 9334
  1: 
    IP: "68.183.229.181"
    NODE_PORT: 9001
    RPC_PORT: 9335
  2: 
    IP: "68.183.229.181"
    NODE_PORT: 9002
    RPC_PORT: 9336
  3: 
    IP: "68.183.229.181"
    NODE_PORT: 9003
    RPC_PORT: 9337
shard:
  0: 
    0: 
      IP: "68.183.189.178"
      NODE_PORT: 19004
      RPC_PORT: 19334
    1: 
      IP: "68.183.189.178"
      NODE_PORT: 19005
      RPC_PORT: 19335
    2: 
      IP: "68.183.183.131"
      NODE_PORT: 19004
      RPC_PORT: 19334
    3: 
      IP: "68.183.183.131"
      NODE_PORT: 19005
      RPC_PORT: 19335
  1:
    0: 
      IP: "157.230.33.30"
      NODE_PORT: 29000
      RPC_PORT: 29334
    1: 
      IP: "157.230.33.30"
      NODE_PORT: 29001
      RPC_PORT: 29335
    2: 
      IP: "157.230.33.62"
      NODE_PORT: 29000
      RPC_PORT: 29334
    3: 
      IP: "157.230.33.62"
      NODE_PORT: 29001
      RPC_PORT: 29335
fullnode:
  0:
    IP: "128.199.150.40"
    NODE_PORT: 19004
    RPC_PORT: 19334
  1: 
    IP: "128.199.150.40"
    NODE_PORT: 19005
    RPC_PORT: 19335
KEY:
  beacon:
    0: '112t8ruLZgaV3ze37GRikKn8QVnrJDJ5C9Dhtou66vyeBfBDSJ6ZGRSg3k4qTwTjm14kgvwuFX3aAqeU64cGiixDh1ip4nvnmW7xHbSuXpwB'
    1: '112t8rwFSJ8rQ2nuQRH28tgsy5GufZhfQUDQsURdjdDG2jtUyE8ScDGjQNivmFkEJi7HeYX259xYv3tfBir9GPskF9tjEHxp4HcVK2w3rmxJ'
    2: '112t8rnyr3YjfpLN9unAvAM2TGZhurt7gfcrjCkUv11DWf6gN79raFqrazCHArWsWyosZvGdw5s5cuzzYXgpxDj9sEieyKqKCZ97inpaAXUR'
    3: "112t8rzcRLXhra2ouQo4yCZiQt1iEoZdRkD3m6fixXqCLzygjo28L3isePdPjPbXJ7zcxgyxbiNuF4Ex15NFCHVLwHhJD7QL7AHUfUsH78AP"
  shard:
    0:
      0: '112t8rqJHgJp2TPpNpLNx34aWHB5VH5Pys3hVjjhhf9tctVeCNmX2zQLBqzHau6LpUbSV52kXtG2hRZsuYWkXWF5kw2v24RJq791fWmQxVqy'
      1: '112t8rrEEcDQBMnUM5J17qniHZZmckmr8LGCv9nBjP9x5wmGFGUryKTNvEAf1jh2wwW69rxwtANq4m8JmzowfKVPayUHPmAKdwQw5718GKuH'
      2: '112t8rnXgYcLCjeHBpnesutJEBfG5xVzhMf8gLVZuL4fya4ov9Ko8pr6Mrj5eEZe5bie4ZVnH7MQNpLjuAxiuSDmPp5WgkuRRGW8NLcJZoF2'
      3: '112t8rnj1Xs9p5D6ue4fuLnVq9mJz5kKtyRMLEVBr8hxxmgd7haNFhruwezHswtEu9YKgAUWrnPrU1uvJE1gvep2pixy55ctDNc593c5pHmB'
    1:
      0: '112t8rnY5yiM5XJCnAH3hD2UzhKnwoQjPCDDy6cRwsoNevRFJBm7HmYLbpijKvpxG8GD1LsamT9DC6xhs1RqCnDzoDhwFv1sd7ckzSa2Cj16'
      1: '112t8rpDvusPVjYYUECbVd8mSFq9iijuJHtbX2yrEwNT1mebBo8EHAe9neFPNfmd6VmdzAZDHP5ei8QDMxLXE1HRHEqo21gi3twYm8JFiFxJ'
      2: '112t8rq772Lr6tsEri2smLpG5s3v1LrtLNyu9eAavAJk4yMcWz6ziZPoB2sVt8SAjtPY3KT3oGAWXiszXBWXfQxXumJDvgD1rckwiGsS73XU'
      3: '112t8rwRDxAWzCyCq2tp2T4zVXwCpG75crEdKx84TuJNFzeKMiVb1KU65XkwYFB9o4bnJQpt941ptScuTAnHWJ3XJkN9ofWehHdUqzNfQfCt'
  fullnode:
    0: ''
    1: ''