---
- hosts: all
  gather_facts: no
  serial: 30
  tasks:
    - name: Remove container
      shell: |
        docker rm -f {{inventory_hostname}}; echo 1

    - name: Deploy full node
      shell: |
         docker run --net host -e NAME={{inventory_hostname}} -e GRAFANAURL={{GrafanaURL}} -e DISCOVERPEERSADDRESS='{{bootnode}}:9330' -v /data/{{inventory_hostname}}:/data -e EXTERNALADDRESS='{{ansible_ssh_host}}' -e PORT='{{node_port}}' -e RPC_PORT='{{rpc_port}}' -d --name {{inventory_hostname}} hungngoautonomous/constant /run_fullnode.sh y || docker restart {{inventory_hostname}} 
      when: inventory_hostname == "fullnode0" or inventory_hostname == "fullnode1"

    # - name: restart
    #   shell: |
    #     docker restart {{inventory_hostname}} 