---
- hosts: all
  gather_facts: no
  serial: 20
  

  vars_prompt:
    - name: "clear"
      prompt: "Clear all data data? [Y/n]"
      

  tasks:
    - name: Deploy bootnode 
      shell: |
        docker rm -f local-bootnode ; docker run -p 9330:9330 -e PORT='9330' --name {{inventory_hostname}} -d constant /run_bootnode.sh; echo 1
      when: inventory_hostname == "local-bootnode" 

    - name: Stop 
      shell: |
        docker rm -f {{inventory_hostname}} ; echo 1
      when: inventory_hostname != "local-bootnode"

    - name: Deploy full node
      shell: |
        docker run --net host -e NAME={{inventory_hostname}} -e DISCOVERPEERSADDRESS='{{bootnode}}:9330' -v /data/{{inventory_hostname}}:/data -e PRIVATEKEY='{{privatekey}}' -e EXTERNALADDRESS='{{externaladdress}}'  -e PORT='{{node_port}}' -e RPC_PORT='{{rpc_port}}' -d --name {{inventory_hostname}} constant /run_constant.sh {{clear}}
      when: inventory_hostname != "local-bootnode"