[metric:children]
beacon
shard0
shard1
boot
fullnode

[boot]
bootnode ansible_ssh_host={{beacon.0.IP}} 

[beacon]
beacon0 ansible_ssh_host={{beacon.0.IP}} privatekey={{KEY.beacon.0}} node_port={{beacon.0.NODE_PORT}} rpc_port={{beacon.0.RPC_PORT}} GrafanaURL=""
beacon1 ansible_ssh_host={{beacon.1.IP}} privatekey={{KEY.beacon.1}} node_port={{beacon.1.NODE_PORT}} rpc_port={{beacon.1.RPC_PORT}} GrafanaURL=""
beacon2 ansible_ssh_host={{beacon.2.IP}} privatekey={{KEY.beacon.2}} node_port={{beacon.2.NODE_PORT}} rpc_port={{beacon.2.RPC_PORT}} GrafanaURL=""
beacon3 ansible_ssh_host={{beacon.3.IP}} privatekey={{KEY.beacon.3}} node_port={{beacon.3.NODE_PORT}} rpc_port={{beacon.3.RPC_PORT}} GrafanaURL=""
[shard0]
shard0-0 ansible_ssh_host={{shard.0.0.IP}} privatekey={{KEY.shard.0.0}} node_port={{shard.0.0.NODE_PORT}} rpc_port={{shard.0.0.RPC_PORT}} GrafanaURL=""
shard0-1 ansible_ssh_host={{shard.0.1.IP}} privatekey={{KEY.shard.0.1}} node_port={{shard.0.1.NODE_PORT}} rpc_port={{shard.0.1.RPC_PORT}} GrafanaURL="" 
shard0-2 ansible_ssh_host={{shard.0.2.IP}} privatekey={{KEY.shard.0.2}} node_port={{shard.0.2.NODE_PORT}} rpc_port={{shard.0.2.RPC_PORT}} GrafanaURL=""
shard0-3 ansible_ssh_host={{shard.0.3.IP}} privatekey={{KEY.shard.0.3}} node_port={{shard.0.3.NODE_PORT}} rpc_port={{shard.0.3.RPC_PORT}} GrafanaURL=""
shard0-4 ansible_ssh_host={{shard.0.4.IP}} privatekey={{KEY.shard.0.4}} node_port={{shard.0.4.NODE_PORT}} rpc_port={{shard.0.4.RPC_PORT}} GrafanaURL=""
shard0-5 ansible_ssh_host={{shard.0.5.IP}} privatekey={{KEY.shard.0.5}} node_port={{shard.0.5.NODE_PORT}} rpc_port={{shard.0.5.RPC_PORT}} GrafanaURL="" 
shard0-6 ansible_ssh_host={{shard.0.6.IP}} privatekey={{KEY.shard.0.6}} node_port={{shard.0.6.NODE_PORT}} rpc_port={{shard.0.6.RPC_PORT}} GrafanaURL=""
shard0-7 ansible_ssh_host={{shard.0.7.IP}} privatekey={{KEY.shard.0.7}} node_port={{shard.0.7.NODE_PORT}} rpc_port={{shard.0.7.RPC_PORT}} GrafanaURL=""

[shard1]
shard1-0 ansible_ssh_host={{shard.1.0.IP}} privatekey={{KEY.shard.1.0}} node_port={{shard.1.0.NODE_PORT}} rpc_port={{shard.1.0.RPC_PORT}} GrafanaURL=""
shard1-1 ansible_ssh_host={{shard.1.1.IP}} privatekey={{KEY.shard.1.1}} node_port={{shard.1.1.NODE_PORT}} rpc_port={{shard.1.1.RPC_PORT}} GrafanaURL=""
shard1-2 ansible_ssh_host={{shard.1.2.IP}} privatekey={{KEY.shard.1.2}} node_port={{shard.1.2.NODE_PORT}} rpc_port={{shard.1.2.RPC_PORT}} GrafanaURL=""
shard1-3 ansible_ssh_host={{shard.1.3.IP}} privatekey={{KEY.shard.1.3}} node_port={{shard.1.3.NODE_PORT}} rpc_port={{shard.1.3.RPC_PORT}} GrafanaURL=""
shard1-4 ansible_ssh_host={{shard.1.4.IP}} privatekey={{KEY.shard.1.4}} node_port={{shard.1.4.NODE_PORT}} rpc_port={{shard.1.4.RPC_PORT}} GrafanaURL=""
shard1-5 ansible_ssh_host={{shard.1.5.IP}} privatekey={{KEY.shard.1.5}} node_port={{shard.1.5.NODE_PORT}} rpc_port={{shard.1.5.RPC_PORT}} GrafanaURL=""
shard1-6 ansible_ssh_host={{shard.1.6.IP}} privatekey={{KEY.shard.1.6}} node_port={{shard.1.6.NODE_PORT}} rpc_port={{shard.1.6.RPC_PORT}} GrafanaURL=""
shard1-7 ansible_ssh_host={{shard.1.7.IP}} privatekey={{KEY.shard.1.7}} node_port={{shard.1.7.NODE_PORT}} rpc_port={{shard.1.7.RPC_PORT}} GrafanaURL=""

[fullnode]
fullnode0 ansible_ssh_host={{fullnode.0.IP}} node_port={{fullnode.0.NODE_PORT}} rpc_port={{fullnode.0.RPC_PORT}} GrafanaURL=http://128.199.96.206:8086/write?db=mydb
fullnode1 ansible_ssh_host={{fullnode.1.IP}} node_port={{fullnode.1.NODE_PORT}} rpc_port={{fullnode.1.RPC_PORT}} GrafanaURL=""